# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.14
        python -m poetry poetry install
    - uses: psf/black@stable
      with:
        black_args: ". --check"
    - name: Test with pytest
      run: |
        python -m poetry run python -m pytest -v